<?php echo $this->doctype() . "\n"; ?>
<html lang="en">
<head>
<?php echo $this->headTitle() . "\n"; ?>

<!-- Javascript -->
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<?php echo $this->headScript() . "\n"; ?>

<!-- Stylesheets -->
<?php echo $this->headLink() . "\n"; ?>

<!-- Shortcut icon -->
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

<!-- Meta tags -->
<?php echo $this->headMeta() . "\n"; ?>
</head>
<body>
	<header>
		<h1>Zend Framework HTML5 project</h1>
		<nav>
			<ul>
				<li><a href="javascript:;">Menu item 1</a></li>
				<li><a href="javascript:;">Menu item 2</a></li>
				<li><a href="javascript:;">Menu item 3</a></li>
			</ul>
		</nav>
	</header>
	<?php echo $this->layout()->content; ?>
	<footer>
		Some footer text...
	</footer>
</body>
</html>